'use strict';
// Metadados das ferramentas (sem componentes). Compartilhado pela janela principal
// (src/tools/registry.js, que associa cada id ao componente) e pela command palette,
// que assim não precisa empacotar as telas das ferramentas.
const TOOL_META = [
  {
    id: 'sql',
    name: 'SQL Formatter',
    icon: 'database',
    group: 'Texto & código',
    desc: 'Formata e indenta SQL no padrão do sqlformat.org',
    shortcutKey: '1',
    keywords: ['query', 'consulta', 'sqlformat', 'sqlparse', 'indentar', 'beautify'],
  },
  {
    id: 'xml',
    name: 'XML Formatter',
    icon: 'code-xml',
    group: 'Texto & código',
    desc: 'Formata e indenta XML nos moldes do vscode-xml (LemMinX)',
    shortcutKey: '2',
    keywords: ['lemminx', 'soap', 'wsdl', 'xsd', 'indentar', 'beautify', 'pretty'],
  },
  {
    id: 'diff',
    name: 'Diff Checker',
    icon: 'git-compare',
    group: 'Texto & código',
    desc: 'Compara dois textos lado a lado, com destaque por caractere e merge',
    shortcutKey: '3',
    keywords: ['comparar', 'compare', 'diferença', 'diffchecker', 'merge', 'mesclar'],
  },
  {
    id: 'json',
    name: 'JSON Visualizer',
    icon: 'braces',
    group: 'Texto & código',
    desc: 'Edita, formata e explora JSON como grafo, árvore, YAML ou CSV (estilo JSON Crack)',
    shortcutKey: '6',
    keywords: ['jsoncrack', 'json crack', 'grafo', 'graph', 'árvore', 'tree', 'jsonpath', 'yaml', 'csv', 'minificar', 'beautify', 'formatar'],
  },
  {
    id: 'git',
    name: 'Git',
    icon: 'git-branch',
    group: 'Texto & código',
    desc: 'Repositórios locais: grafo do histórico, mudanças por trecho, branches, stash e desfazer qualquer coisa',
    shortcutKey: '8',
    keywords: ['git', 'commit', 'branch', 'stash', 'merge', 'rebase', 'reflog', 'historico', 'repositório', 'versionamento', 'desfazer', 'diff'],
  },
  {
    id: 'notes',
    name: 'Notes',
    icon: 'notebook-pen',
    group: 'Conhecimento',
    desc: 'Memória técnica: notas em Markdown, snippets e busca',
    shortcutKey: '4',
    keywords: ['anotações', 'notas', 'snippets', 'conhecimento', 'markdown', 'wiki'],
  },
  {
    id: 'vault',
    name: 'Vault',
    icon: 'vault',
    group: 'Conhecimento',
    desc: 'Cofre de senhas e tokens: criptografado com senha mestra, cópia que se apaga sozinha',
    shortcutKey: '7',
    keywords: ['cofre', 'senha', 'senhas', 'password', 'credenciais', 'segredo', 'secret', 'token', 'banco', 'connection string', 'login'],
  },
  {
    id: 'devcore',
    name: 'DevCore',
    icon: 'cpu',
    group: 'DevCore',
    desc: 'Infraestrutura idle com DevPets — cresce sozinha enquanto você trabalha',
    shortcutKey: '5',
    keywords: ['idle', 'devpets', 'pets', 'jogo', 'incremental', 'compute', 'infraestrutura'],
  },
];

module.exports = { TOOL_META };
